### ISSUE TITLE
[Failed compilation] Undefined string type (probably missing includes)

### ISSUE THREAD

**Issue by Romop5** [dormon/Vars#4]
When compiling with both clang++ and g++, I run into compilation errors in `Directory.h`, but also in `Caller.h`.

**clang++ version**: clang version 10.0.0 (Fedora 10.0.0-2.fc32)
**g++ version**: g++ (GCC) 10.2.1 20200723 (Red Hat 10.2.1-1)

Here's my fix which worked for me (but could have introduce includes where it is not necessary):
```diff
diff --git a/src/Vars/Caller.h b/src/Vars/Caller.h
index aad31cd..2f63ca0 100644
--- a/src/Vars/Caller.h
+++ b/src/Vars/Caller.h
@@ -2,6 +2,7 @@
 
 #include <Vars/Fwd.h>
 #include <Vars/vars_export.h>
+#include <string>
 
 class vars::Caller{
   public:
diff --git a/src/Vars/Directory.h b/src/Vars/Directory.h
index 4c0bf0f..e8c0d54 100644
--- a/src/Vars/Directory.h
+++ b/src/Vars/Directory.h
@@ -3,6 +3,7 @@
 #include <Vars/Fwd.h>
 #include <map>
 #include <set>
+#include <string>
 
 using namespace std;
```

**Comment by Romop5** [comment]
Bump (still needed to compile your checkRepos at Linux)

**Comment by dormon** [comment]
Fixed
